#!/usr/bin/env ruby
# -*- mode: ruby;-*-

require 'optparse'
require './lib/compiler'
require './lib/vm'

def main()
  opt = OptionParser.new
  opt.on('--dump-ir')
  params = {}
  opt.parse!(ARGV, into: params)

  compiler = Compiler.new()
  bbcon = compiler.compile(ARGV[0])
  if params[:"dump-ir"]
    bbcon.dump()
    return
  end

  vm = VM.new()
  result = vm.run(bbcon.bbs)
  p result
end

if $0 == __FILE__
  main()
end
