#!/usr/bin/env ruby
# -*- mode: ruby;-*-

require './lib/compiler'
require './lib/vm'

def main()
  compiler = Compiler.new()
  bbcon = compiler.compile(ARGV[0])
  bbcon.dump()

  vm = VM.new()
  result = vm.run(bbcon.bbs)
  p result
end

if $0 == __FILE__
  main()
end
